name: deepberlin
channels:
  - defaults
dependencies:
  - ca-certificates=2019.5.15=0
  - certifi=2019.6.16=py37_0
  - dask-core=2.1.0=py_0
  - dbus=1.13.6=h746ee38_0
  - decorator=4.4.0=py37_1
  - defusedxml=0.6.0=py_0
  - expat=2.2.6=he6710b0_0
  - ffmpeg=4.0=hcdf2ecd_0
  - fontconfig=2.13.0=h9420a91_0
  - hdf5=1.10.2=hba1933b_1
  - imageio=2.5.0=py37_0
  - ipykernel=5.1.1=py37h39e3cac_0
  - ipython=7.6.1=py37h39e3cac_0
  - jupyter_client=5.3.1=py_0
  - jupyter_core=4.5.0=py_0
  - matplotlib=3.1.0=py37h5429711_0
  - nbconvert=5.5.0=py_0
  - nbformat=4.4.0=py37_0
  - networkx=2.3=py_0
  - notebook=6.0.0=py37_0
  - numpy=1.16.4=py37h7e9f1db_0
  - opencv=3.4.2=py37h6fd60c2_1
  - pandas=0.24.2=py37he6710b0_0
  - python=3.7.3=h0371630_0
  - scikit-image=0.15.0=py37he6710b0_0
  - scipy=1.3.0=py37h7c811a0_0
  - seaborn=0.9.0=py37_0
  - pip:
    - awscli==1.16.205
    - botocore==1.12.195
    - click==7.0
    - cookiecutter==1.6.0
    - coverage==4.5.3
    - docutils==0.15.1
    - flake8==3.7.8
    - imagesize==1.1.0
    - kaggle==1.5.4
    - packaging==19.0
    - pathlib2==2.3.4
    - pip==19.2.1
    - python-dotenv==0.10.3
    - python-slugify==3.0.2
    - pyyaml==5.1
    - requests==2.22.0
    - sphinx==2.1.2
    - tqdm==4.32.2
    - urllib3==1.24.3

